# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 340e271807c18fc7ac77b35608bcce3433589938626a06e49ce13b074a08b8d893b8874cd730c0cc64ea7ff304857e75be1a83f98742122c287bb5b7056a3113

test:
  secret_key_base: 3687e689c603e842ad4a357d12cf3b44147964e8bf7ca1577acd03f0675470868ac85cc4cd8fc720dec3672cc10c5943405b27933d9812f4fddf57a9177c39e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
